-- Основная таблица бронирований
CREATE TABLE IF NOT EXISTS orders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    room_id             BIGINT NOT NULL,
    order_status        VARCHAR(16) NOT NULL,
    order_price         NUMERIC(19, 2) NOT NULL,
    order_start_date    TIMESTAMPTZ NOT NULL,
    order_end_date      TIMESTAMPTZ NOT NULL,
    created_at          TIMESTAMPTZ DEFAULT current_timestamp,
    updated_at          TIMESTAMPTZ DEFAULT current_timestamp
);
