-- Основная таблица апартаментов
CREATE TABLE IF NOT EXISTS rooms (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apartment_name  VARCHAR(64) NOT NULL,
    city            VARCHAR(64) NOT NULL,
    number_of_rooms SMALLINT NOT NULL,
    price           NUMERIC(19, 2) NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT current_timestamp,
    updated_at      TIMESTAMPTZ DEFAULT current_timestamp
);